#!/usr/bin/env bash
# Transfer a file from our client to a server

num_args=$#

if [ $num_args -eq 4 ];
then
	scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi
